// <auto-generated />
using CarpatiansWalksAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WalkAPI.Migrations
{
    [DbContext(typeof(CarpatianWalksDbContext))]
    partial class CarpatianWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarpatiansWalksAPI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HowToGetHere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Places")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HowToGetHere = "Using train from Lviv or Ivano-Frankivsk is very conveniet and preferable",
                            Name = "Lazeshchyna (Yasinna)",
                            Places = "You can get to mountais Kukul, Petros, Drahobrat, it`s waterfall, lake Ivor and waterfall Trufanets, "
                        },
                        new
                        {
                            Id = 2,
                            HowToGetHere = "Using regular (12:00, 15:00 am) bus from Verhovyna, Verhovyna can be reached from Ivano-Frankivsk using bus",
                            Name = "Dzembronya",
                            Places = "Able to reach awesome mountain Pip Ivan, Dzembronya and it`s waterfall and even second biggest mountain -- Brebenescyl"
                        },
                        new
                        {
                            Id = 3,
                            HowToGetHere = "Using train or bus to Vorohta, then catching taxi or unregular bus to base Zaroslak",
                            Name = "Zaroslak",
                            Places = "Visit Hoverla, polonuna Pozhyzhevska, lake Nesamovute, mountains Rebra, Hytun-Tomnatyk, Shputzi"
                        },
                        new
                        {
                            Id = 4,
                            HowToGetHere = "Using bus from IvanoFrankivsk or train from Frankivsk, Lviv, other cities",
                            Name = "Yaremche",
                            Places = "You can visit various waterfalls, old aqueducs, polonynas and small mountain"
                        });
                });

            modelBuilder.Entity("CarpatiansWalksAPI.Models.Walk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("Elevation")
                        .HasColumnType("int");

                    b.Property<string>("JsonImageURLs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonMoutains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("CarpatiansWalksAPI.Models.Walk", b =>
                {
                    b.HasOne("CarpatiansWalksAPI.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
